export default { 
    up:"CREATE TABLE IF NOT EXISTS  users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,username VARCHAR(255), email VARCHAR(255)  , password VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",
    down:"DROP TABLE users" 
}
    