export default { 
    up:"CREATE TABLE IF NOT EXISTS personal_access_tokens ( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,token VARCHAR(255),expired_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT FK_user FOREIGN KEY (user_id) REFERENCES users(id));",
    down:"DROP TABLE personal_access_tokens" 
}
    